use schema snowflake_sample_data.tpcds_sf10tcl;

SHOW DATABASES;
SHOW SCHEMAS in DATABASE;

SHOW TABLES in SCHEMA;
SHOW COLUMNS in SCHEMA;
SHOW PRIMARY KEYS in SCHEMA;
SHOW UNIQUE KEYS in SCHEMA;
SHOW IMPORTED KEYS in SCHEMA;

SHOW ROLES;
SHOW GRANTS TO ROLE role2;

SHOW USERS;
SHOW GRANTS TO USER cristiscu;
