CALL SNOWFLAKE.LOCAL.ACCOUNT_ROOT_BUDGET
    !ACTIVATE();

CALL SNOWFLAKE.LOCAL.ACCOUNT_ROOT_BUDGET
    !SET_SPENDING_LIMIT(1000);

CREATE NOTIFICATION INTEGRATION budgets_notif_integration
    TYPE=EMAIL
    ENABLED=TRUE
    ALLOWED_RECIPIENTS=('email1@gmail.com', 'email2@gmail.com');
GRANT USAGE ON INTEGRATION budgets_notif_integration
    TO APPLICATION snowflake;

CALL SNOWFLAKE.LOCAL.ACCOUNT_ROOT_BUDGET
    !SET_EMAIL_NOTIFICATIONS(
        'budgets_notif_integration',
        'email1@gmail.com, email2@gmail.com');

CALL SNOWFLAKE.LOCAL.ACCOUNT_ROOT_BUDGET
    !SET_NOTIFICATION_MUTE_FLAG(TRUE);

CALL SNOWFLAKE.LOCAL.ACCOUNT_ROOT_BUDGET
    !GET_CONFIG();
